const engUnits = {
  bag: ['bag', 'bags'],
  box: ['box', 'boxes'],
  bottle: ['bottle', 'bottles'],
  can: ['can', 'cans'],
  cup: ['cup', 'c', 'c.', 'C', 'Cups', 'cups'],
  clove: ['clove'],
  gallon: ['gallon', 'gal', 'gallons'],
  ounce: ['ounce', 'ounces', 'oz', 'oz.', 'ozs'],
  pint: ['pint', 'pt', 'pts', 'pt.', 'pints'],
  pound: ['pound', 'lb', 'lb.', 'lbs', 'lbs.', 'Lb', 'Lbs', 'pounds'],
  quart: ['quart', 'qt', 'qt.', 'qts', 'qts.', 'quarts'],
  tablespoon: ['tbs', 'tbsp', 'tbsp.', 'Tbsp.', 'tbspn', 'Tablespoons', 'Tablespoon'],
  teaspoon: ['teaspoon', 'teaspoons', 'Tsp', 'tsp', 'tsp.', 'tspn', 'tsps', 'tspns'],
  gram: ['gram', 'grams', 'g', 'g.'],
  kilogram: ['kilogram', 'kg', 'kg.', 'Kg', 'Kg.', 'kilograms'],
  liter: ['liter', 'l', 'l.', 'lt', 'Lt', 'LT', 'L', 'L.', 'liters'],
  milligram: ['milligram', 'mg', 'mg.', 'mgs', 'milligrams'],
  milliliter: ['milliliter', 'ml', 'ml.', 'mL', 'mL.', 'mls', 'milliliters'],
  package: ['package', 'pkg', 'pkgs', 'packages'],
  stick: ['stick', 'sticks'],
  piece: ['piece', 'pcs', 'pcs.', 'pieces'],
  pinch: ['pinch'],
  small: ['Small'],
  slice: ['slice', 'slices'],
  medium: ['Medium'],
  large: ['large', 'Large'],
  jar: ['jar', 'jar.', 'jars'],
  dozen: ['dozen', 'Dozen', 'dzn'],
  sprig: ['sprig', 'Sprig', 'sprigs'],
  sprinkle: ['sprinkle', 'sprinkles'],
  yard: ['yard', 'yards', 'yd', 'yds', 'yd.'],
  fluid_ounce: ['fluid ounce', 'fluid ounces', 'fl. oz', 'fl oz', 'floz'],
  carton: ['carton', 'cartons', 'ctn', 'ctns'],
  bulb: ['bulb', 'bulbs', 'bulb.'],
  stem: ['stem', 'stems'],
  tube: ['tub', 'tubs', 'tube', 'tubes'],
  grain: ['grain', 'grains'],
  bar: ['bar', 'bars'],
  barrel: ['barrel', 'barrels', 'bbl', 'bbls'],
  centiliter: ['centiliter', 'centiliters', 'cl', 'cls'],
  inch: ['inch', 'inches', 'in', 'ins'],
  foot: ['foot', 'feet', 'ft'],
  meter: ['meter', 'meters'],
  centimeter: ['centimeter', 'centimeters', 'cm', 'cms'],
  millimeter: ['millimeter', 'millimeters', 'mm', 'mms'],
  serving: ['serving', 'servings', 'serv', 'servs'],
  canister: ['canister', 'canisters'],
  unit_square: ['unit square', 'sq'],
  furlong: ['furlong', 'furlongs', 'fur'],
  dash: ['dash', 'dashes'],
  stone: ['stone', 'stones', 'st', 'sts'],
  ton: ['ton', 'tons'],
  square: ['square', 'squares', 'sq', 'sqs'],
  bunch: ['bunch', 'bunches'],
  garnish: ['garnish'],
  crate: ['crate', 'crates'],
  drop: ['drop', 'drops'],
  handful: ['handful', 'handfuls'],
  roll: ['roll', 'rolls'],
  case: ['case', 'cases'],
  packet: ['packet', 'packets', 'pkt', 'pkts', 'pckt', 'pckts'],
  pair: ['pair', 'pairs'],
  to_taste: ['to taste'],
  whole: ['whole'],
  stalk: ['stalk', 'stalks'],
  loaf: ['loaf', 'loaves'],
  link: ['link', 'links'],
  leaf: ['leaf', 'leaves'],
  heart: ['heart', 'hearts'],
  head: ['head', 'heads'],
  fillet: ['fillet', 'fillets'],
  ear: ['ear', 'ears'],
  cube: ['cube', 'cubes'],
  container: ['container', 'containers'],
  as_needed: ['as needed'],
  pouch: ['pouch', 'pouches'],
  envelope: ['envelope', 'envelopes'],
  pack: ['pack', 'packs'],
  count: ['count', 'ct'],
  each: ['each', 'Each', 'ea', 'ea.'],
};

const engNameToSymbol = {
  cup: 'c',
  gallon: 'gal',
  ounce: 'oz',
  pint: 'pt',
  pound: 'lb',
  quart: 'qt',
  tablespoon: 'tbs',
  teaspoon: 'tsp',
  gram: 'g',
  kilogram: 'kg',
  liter: 'lt',
  milligram: 'mg',
  milliliter: 'ml',
  clove: '',
  bag: '',
  box: '',
  pinch: '',
  can: '',
  slice: '',
  piece: '',
  jar: '',
};

const engPreposition = ['of'];

const unitsMap = new Map();
unitsMap.set("eng", [engUnits, engPreposition, engNameToSymbol]);

const methods = [
  "Diced small",
  "Diced medium",
  "Diced large",
  "Finely diced",
  "Coarsely diced",
  "Diced into triangles",
  "Diced into squares",
  "Diced into rectangles",
  "Diced into cubes",
  "Diced into spheres",
  "Finely grated",
  "Coarsely grated",
  "Finely shredded",
  "Coarsely shredded",
  "Finely sliced",
  "Coarsely sliced",
  "Sliced thin",
  "Sliced thick",
  "Coarsely chopped",
  "Finely chopped",
  "Freshly squeezed",
  "Freshly ground",
  "Freshly grated",
  "Thinly sliced",
  "Chopped",
  "Crushed",
  "Minced",
  "Grated",
  "Ground",
  "Shredded",
  "Fresh",
  "Sliced",
  "Diced",
  "Cut",
  "Peeled",
  "Mashed",
  "Pureed",
  "Blended",
  "Pounded",
  "Stir-fried",
  "Roasted",
  "Baked",
  "Grilled",
  "Sautéed",
  "Steamed",
  "Boiled",
  "Poached",
  "Broiled",
  "Seared",
  "Marinated",
  "Pickled",
  "Fermented",
  "Preserved",
  "Stewed",
  "Braised",
  "Stuffed",
  "Wrapped",
  "Stirred",
  "Whisked",
  "Folded",
  "Beaten",
  "Mixed",
  "Kneaded",
  "Sifted",
  "Sugared",
  "Peppered",
  "Herbed",
  "Spiced",
  "Flavored",
  "Seasoned",
  "Smoked",
  "Glazed",
  "Squeshed",
  "Coated",
  "Breaded",
  "Dipped",
  "Drizzled",
  "Poured",
  "Sprinkled",
  "Garnished",
  "Decorated",
  "Zest of",
  "Plated",
  "Served",
  "Stirred",
  "Whipped",
  "Fold",
  "Julienned",
  "Cubed",
  "Kosher"
]

module.exports = {
  unitsMap,
  engUnits,
  engNameToSymbol,
  engPreposition,
  unitsMap,
  methods
}