const engUnits = {
  bag: ['bag', 'bags'],
  box: ['box'],
  bottle: ['bottle', 'bottles'],
  can: ['can'],
  cup: ['cup', 'c', 'c.', 'C', 'Cups', 'cups'],
  clove: ['clove'],
  each: ['each', 'Each', 'ea', 'ea.'],
  gallon: ['gallon', 'gal'],
  ounce: ['ounce', 'ounces', 'oz', 'oz.', 'ozs'],
  pint: ['pint', 'pt', 'pts', 'pt.'],
  pound: ['pound', 'lb', 'lb.', 'lbs', 'lbs.', 'Lb', 'Lbs'],
  quart: ['quart', 'qt', 'qt.', 'qts', 'qts.'],
  tablespoon: ['tbs', 'tbsp', 'tbspn', 'Tablespoons', 'Tablespoon'],
  teaspoon: ['teaspoon', 'teaspoons', 'tsp', 'tspn', 'tsps', 'tspns'],
  gram: ['gram', 'g', 'g.'],
  kilogram: ['kilogram', 'kg', 'kg.', 'Kg', 'Kg.'],
  liter: ['liter', 'l', 'l.', 'lt', 'Lt', 'LT', 'L', 'L.'],
  milligram: ['milligram', 'mg', 'mg.'],
  milliliter: ['milliliter', 'ml', 'ml.', 'mL', 'mL.'],
  package: ['package', 'pkg', 'pkgs'],
  stick: ['stick', 'sticks'],
  piece: ['piece', 'pcs', 'pcs.'],
  pinch: ['pinch'],
  small: ['Small'],
  slice: ['slice'],
  medium: ['Medium'],
  large: ['large', 'Large'],
  jar: ['jar', 'jar.', 'jars'],
  dozen: ['dozen', 'Dozen'],
  sprig: ['sprig', 'Sprig'],
  yard: ['yard', 'yards', 'yd', 'yds', 'yd.'],
  fluid_ounce: ['fluid ounce', 'fluid ounces', 'fl. oz'],
  carton: ['carton', 'cartons', 'ctn', 'ctns'],
  bulb: ['bulb', 'bulbs', 'bulb.'],
  stem: ['stem', 'stems'],
  tube: ['tub', 'tubs', 'tube', 'tubes'],
  grain: ['grain', 'grains'],
  bar: ['bar', 'bars'],
  barrel: ['barrel', 'barrels', 'bbl', 'bbls'],
  centiliter: ['centiliter', 'centiliters', 'cl', 'cls'],
  inch: ['inch', 'inches', 'in', 'ins'],
  foot: ['foot', 'feet', 'ft'],
  meter: ['meter', 'meters'],
  centimeter: ['centimeter', 'centimeters', 'cm', 'cms'],
  millimeter: ['millimeter', 'millimeters', 'mm', 'mms'],
  serving: ['serving', 'servings', 'serv', 'servs'],
  canister: ['canister', 'canisters'],
  unit_square: ['unit square', 'sq'],
  furlong: ['furlong', 'furlongs', 'fur'],
  dash: ['dash'],
  stone: ['stone', 'stones', 'st', 'sts'],
  ton: ['ton', 'tons'],
  square: ['square', 'squares', 'sq', 'sqs'],
  bunch: ['bunch', 'bunches'],
  garnish: ['garnish'],
  crate: ['crate', 'crates'],
  drop: ['drop', 'drops'],
  handful: ['handful', 'handfuls'],
  roll: ['roll', 'rolls'],
  case: ['case', 'cases'],
  packet: ['packet', 'packets', 'pkt', 'pkts', 'pckt', 'pckts'],
  pair: ['pair', 'pairs'],
  to_taste: ['to taste'],
  whole: ['whole'],
  stalk: ['stalk', 'stalks'],
  loaf: ['loaf', 'loaves'],
  link: ['link', 'links'],
  leaf: ['leaf', 'leaves'],
  heart: ['heart', 'hearts'],
  head: ['head', 'heads'],
  fillet: ['fillet', 'fillets'],
  ear: ['ear', 'ears'],
  cube: ['cube', 'cubes'],
  container: ['container', 'containers'],
  as_needed: ['as needed'],
  pouch: ['pouch', 'pouches'],
  envelope: ['envelope', 'envelopes'],
  medium: ['medium'],
  pack: ['pack', 'packs'],
  count: ['count', 'ct']
};

const engNameToSymbol = {
  cup: 'c',
  gallon: 'gal',
  ounce: 'oz',
  pint: 'pt',
  pound: 'lb',
  quart: 'qt',
  tablespoon: 'tbs',
  teaspoon: 'tsp',
  gram: 'g',
  kilogram: 'kg',
  liter: 'lt',
  milligram: 'mg',
  milliliter: 'ml',
  clove: '',
  bag: '',
  box: '',
  pinch: '',
  can: '',
  slice: '',
  piece: '',
  jar: '',
};

const engPreposition = ['of'];

const unitsMap = new Map();
unitsMap.set("eng", [engUnits, engPreposition, engNameToSymbol]);

module.exports = {
  unitsMap,
  engUnits,
  engNameToSymbol,
  engPreposition,
  unitsMap
}